### ISSUE TITLE
Nota para la profesora

### ISSUE THREAD

**Issue by Mariarendon312** [Mariarendon312/PDS_Proyecto#7]

**Comment by Mariarendon312** [comment]
Todos lo hicimos, Daniel no aparece porque no le dio para acepatar la invitaición, solucionaremos eso lo antes posible.

**Comment by Misja343** [comment]
Daniel ya ha sido añadido al grupo de trabajo, ya aparecemos todos en GitHub

**Comment by Misja343** [comment]
Profesora si encuentra un CC.java en el repositorio era una practica para entender, por alguna razon este no se de deja eliminar, cuando sea posible este sera removido. Agradezco su atencion.
